# Generated by Django 4.1.5 on 2023-01-31 10:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gebieden",
            fields=[
                ("xid", models.BigAutoField(primary_key=True, serialize=False)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=28992)),
                ("id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Lastbeperking",
            fields=[
                ("p_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("link_nr", models.IntegerField()),
                ("lastbeperking_in_kg", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stremmingen",
            fields=[
                (
                    "p_id",
                    models.BigAutoField(
                        help_text="Added by opdrachtenteam",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link_nr", models.IntegerField(db_index=True, help_text="vma_linknr")),
                ("werkzaamheden", models.CharField(max_length=255)),
                ("opmerking", models.CharField(blank=True, max_length=1000, null=True)),
                ("kenmerk", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="VenstertijdWegen",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("link_nr", models.IntegerField(help_text="linknr")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("e_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "verkeersbord",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dagen", models.TextField(max_length=255)),
                ("begin_tijd", models.TimeField(blank=True, null=True)),
                ("eind_tijd", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VerkeersBorden",
            fields=[
                ("p_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bord_id", models.IntegerField()),
                ("geldigheid", models.CharField(max_length=99)),
                ("rvv_modelnummer", models.CharField(max_length=25)),
                ("tekst", models.CharField(blank=True, max_length=25, null=True)),
                ("kijkrichting", models.IntegerField()),
                ("link_nr", models.IntegerField(help_text="script_link_nr")),
                ("link_gevalideerd", models.IntegerField()),
                ("tekst_waarde", models.FloatField(blank=True, null=True)),
                (
                    "onderbord_tekst",
                    models.CharField(blank=True, max_length=299, null=True),
                ),
                (
                    "verkeersbesluit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("versie", models.DateField()),
                ("rd_x", models.IntegerField()),
                ("rd_y", models.IntegerField()),
                ("link_validated_2", models.IntegerField()),
                ("panorama", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=28992),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerkeersTellingen",
            fields=[
                ("xid", models.BigAutoField(primary_key=True, serialize=False)),
                ("volg_nummer", models.IntegerField(help_text="Volgnummer")),
                ("lat", models.FloatField(help_text="Latitude")),
                ("lon", models.FloatField(help_text="Longitude")),
                (
                    "link_nr",
                    models.IntegerField(blank=True, help_text="vma_link_nr", null=True),
                ),
                ("url", models.CharField(max_length=255)),
                (
                    "telpunt_naam",
                    models.CharField(help_text="Telpuntnaam", max_length=255),
                ),
                ("tussen", models.CharField(help_text="Tussen", max_length=255)),
                (
                    "richtingen_1",
                    models.CharField(help_text="Richtingen_1", max_length=255),
                ),
                (
                    "richtingen_2",
                    models.CharField(help_text="Richtingen_2", max_length=255),
                ),
                ("jaar", models.IntegerField()),
                ("storing", models.CharField(help_text="storing", max_length=255)),
                (
                    "type_verkeer",
                    models.CharField(help_text="Type_verkeer", max_length=255),
                ),
                ("langzaam_verkeer", models.BooleanField(help_text="Langzaam_verkeer")),
                ("snel_verkeer", models.BooleanField(help_text="Snel_verkeer")),
                (
                    "bijzonderheden",
                    models.CharField(help_text="Bijzonderheden", max_length=255),
                ),
                (
                    "meet_methode",
                    models.CharField(help_text="Meetmethode", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Verrijking",
            fields=[
                (
                    "p_id",
                    models.BigAutoField(
                        help_text="Added by opdrachtenteam",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link_nr", models.IntegerField()),
                ("binnen_amsterdam", models.BooleanField(blank=True, null=True)),
                ("binnen_polygoon_awb", models.BooleanField(blank=True, null=True)),
                ("milieuzone", models.BooleanField(blank=True, null=True)),
                ("zone_zwaar_verkeer_bus", models.BooleanField(blank=True, null=True)),
                (
                    "zone_zwaar_verkeer_non_bus",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "zone_zwaar_verkeer_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tunnelcategorie_gevaarlijke_stoffen",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                ("tunnelnamen", models.CharField(blank=True, max_length=29, null=True)),
                (
                    "route_gevaarlijke_stoffen",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                (
                    "beleidsnet_auto",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                (
                    "beleidsnet_ov",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                (
                    "beleidsnet_fiets",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                (
                    "beleidsnet_lopen",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                (
                    "hoofdroute_taxi",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                (
                    "touringcar_aanbevolen_routes",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                (
                    "wettelijke_snelheid_actueel",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "wettelijke_snelheid_wens",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "wegcategorie_actueel",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                (
                    "wegcategorie_wens",
                    models.CharField(blank=True, max_length=29, null=True),
                ),
                ("frc", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vma",
            fields=[
                ("gid", models.BigAutoField(primary_key=True, serialize=False)),
                ("link_nr", models.FloatField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("direction", models.FloatField(blank=True, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("anode", models.FloatField(blank=True, null=True)),
                ("bnode", models.FloatField(blank=True, null=True)),
                ("wegtypeab", models.CharField(blank=True, max_length=50, null=True)),
                ("wegtypeba", models.CharField(blank=True, max_length=50, null=True)),
                ("speedab", models.FloatField(blank=True, null=True)),
                ("speedba", models.FloatField(blank=True, null=True)),
                ("wegtype_ab", models.CharField(blank=True, max_length=50, null=True)),
                ("wegtype_ba", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        srid=28992
                    ),
                ),
            ],
        ),
    ]
