# Generated by Django 4.1.5 on 2023-01-11 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bereikbaarheid", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
        CREATE MATERIALIZED VIEW bereikbaarheid_out_vma_undirected AS SELECT v.link_nr::integer AS link_nr,
            v.name,
            v.anode::integer AS source,
            v.bnode::integer AS target,
            v.geom,
            v.wegtype_ab,
            v.wegtype_ba,
            st_length(v.geom) AS lengte,
                CASE
                    WHEN v.speedab IS NULL THEN '-1'::integer::double precision
                    WHEN v.speedab = 0::double precision THEN '-1'::integer::double precision
                    ELSE st_length(v.geom) / (v.speedab / (10000 / 3600)::double precision)
                END AS cost,
                CASE
                    WHEN v.speedba IS NULL THEN '-1'::integer::double precision
                    WHEN v.speedba = 0::double precision THEN '-1'::integer::double precision
                    ELSE st_length(v.geom) / (v.speedba / (10000 / 3600)::double precision)
                END AS reverse_cost,
                CASE
                    WHEN v.speedab IS NULL AND v.speedba IS NULL THEN false
                    WHEN v.speedab = 0::double precision AND v.speedba = 0::double precision THEN false
                    WHEN v.speedab IS NULL AND v.speedba = 0::double precision THEN false
                    WHEN v.speedab = 0::double precision AND v.speedba IS NULL THEN false
                    ELSE true
                END AS car_network,
            b.binnen_amsterdam,
            b.binnen_polygoon_awb,
            b.milieuzone,
            b.zone_zwaar_verkeer_bus,
            b.zone_zwaar_verkeer_non_bus,
            b.zone_zwaar_verkeer_detail,
            b.tunnelcategorie_gevaarlijke_stoffen,
            b.tunnelnamen,
            b.route_gevaarlijke_stoffen,
            b.beleidsnet_auto,
            b.beleidsnet_ov,
            b.beleidsnet_fiets,
            b.beleidsnet_lopen,
            b.hoofdroute_taxi,
            b.touringcar_aanbevolen_routes,
            b.wettelijke_snelheid_actueel,
            b.wettelijke_snelheid_wens,
            b.wegcategorie_actueel,
            b.wegcategorie_wens,
            b.frc,
            '4.50'::text AS vma_netwerk_versie
           FROM bereikbaarheid_vma v
             LEFT JOIN bereikbaarheid_gebied p ON st_dwithin(p.geom, v.geom, 50::double precision) = true
             LEFT JOIN bereikbaarheid_verrijking b ON v.link_nr = b.link_nr::double precision
          WHERE st_intersects(p.geom, v.geom) = true AND (v.wegtypeab::text <> ALL (ARRAY['voedingslink'::character varying, 'BTM'::character varying, 'loop en fietsveer'::character varying, 'trein'::character varying, 'loopverbinding_halte'::character varying, 'tram'::character varying, 'loopverbinding_knoop'::character varying]::text[])) OR st_intersects(p.geom, v.geom) = true AND (v.wegtypeba::text <> ALL (ARRAY['voedingslink'::character varying, 'BTM'::character varying, 'loop en fietsveer'::character varying, 'trein'::character varying, 'loopverbinding_halte'::character varying, 'tram'::character varying, 'loopverbinding_knoop'::character varying]::text[]));
          """
        )
    ]
