# Generated by Django 4.1.5 on 2023-01-11 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bereikbaarheid", "0003_vma_directed_view"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW bereikbaarheid_out_vma_node AS SELECT DISTINCT x.node,
                st_transform(x.geom, 4326)::geometry(Point,4326) AS geom,
                st_transform(x.geom, 28992)::geometry(Point,28992) AS geom_28992
               FROM ( SELECT bereikbaarheid_out_vma_directed.source AS node,
                        st_startpoint(st_linemerge(bereikbaarheid_out_vma_directed.geom)) AS geom
                       FROM bereikbaarheid_out_vma_directed
                    UNION ALL
                     SELECT bereikbaarheid_out_vma_directed.target AS node,
                        st_endpoint(st_linemerge(bereikbaarheid_out_vma_directed.geom)) AS geom
                       FROM bereikbaarheid_out_vma_directed) x;
    """
        )
    ]
