# Generated by Django 4.1.6 on 2023-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bereikbaarheid", "0004_vma_node"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gebieden",
            options={"verbose_name": "Gebied", "verbose_name_plural": "Gebieden"},
        ),
        migrations.AlterModelOptions(
            name="lastbeperking",
            options={
                "verbose_name": "Lastbeperking",
                "verbose_name_plural": "Lastbeperkingen",
            },
        ),
        migrations.AlterModelOptions(
            name="stremmingen",
            options={"verbose_name": "Stremming", "verbose_name_plural": "Stremmingen"},
        ),
        migrations.AlterModelOptions(
            name="venstertijdwegen",
            options={
                "verbose_name": "Venstertijd",
                "verbose_name_plural": "Venstertijdwegen",
            },
        ),
        migrations.AlterModelOptions(
            name="verkeersborden",
            options={
                "verbose_name": "Verkeersbord",
                "verbose_name_plural": "Verkeersborden",
            },
        ),
        migrations.AlterModelOptions(
            name="verkeerstellingen",
            options={
                "verbose_name": "Verkeerstelling",
                "verbose_name_plural": "Verkeerstellingen",
            },
        ),
        migrations.AlterModelOptions(
            name="verrijking",
            options={
                "verbose_name": "Verrijking",
                "verbose_name_plural": "Verrijkingen",
            },
        ),
        migrations.AlterModelOptions(
            name="vma",
            options={"verbose_name": "Vma", "verbose_name_plural": "Vma"},
        ),
        migrations.RemoveField(
            model_name="gebieden",
            name="id",
        ),
        migrations.AlterField(
            model_name="verkeersborden",
            name="bord_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="vma",
            name="link_nr",
            field=models.FloatField(),
        ),
    ]
