# Generated by Django 4.1.7 on 2023-03-27 10:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bereikbaarheid",
            "0005_alter_gebieden_options_alter_lastbeperking_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="venstertijdwegen",
            name="dagen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=10, null=True),
                size=None,
            ),
        ),
    ]
