# Generated by Django 4.1.9 on 2023-06-22 13:01

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bereikbaarheid", "0006_alter_venstertijdwegen_dagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerkeersPalen",
            fields=[
                (
                    "p_id",
                    models.BigAutoField(
                        help_text="Added by opdrachtenteam",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link_nr", models.IntegerField(help_text="linknr")),
                (
                    "paal_nr",
                    models.CharField(
                        blank=True, help_text="paalnummer", max_length=255, null=True
                    ),
                ),
                (
                    "verkeersbord",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dagen",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10), size=None
                    ),
                ),
                ("begin_tijd", models.TimeField()),
                ("eind_tijd", models.TimeField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=28992),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "standplaats",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("jaar_aanleg", models.IntegerField(blank=True, null=True)),
                (
                    "venstertijden",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "toegangssysteem",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("camera", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "beheerorganisatie",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bijzonderheden",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Verkeerspaal",
                "verbose_name_plural": "Verkeerspalen",
            },
        ),
        migrations.AlterModelOptions(
            name="venstertijdwegen",
            options={
                "verbose_name": "Venstertijdweg",
                "verbose_name_plural": "Venstertijdwegen",
            },
        ),
        migrations.AlterField(
            model_name="verrijking",
            name="link_nr",
            field=models.IntegerField(help_text="linknr"),
        ),
    ]
