# Generated by Django 4.1.10 on 2023-10-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bereikbaarheid",
            "0006_lastbeperking_created_at_lastbeperking_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastbeperking",
            name="lastbeperking_in_kg",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
